// apps/react/src/features/registration/components/registrationForm/RegistrationForm.tsx
import { FC, memo } from 'react';
import { SubmitHandler, useForm } from 'react-hook-form';
import { Button, TextField } from '@mui/material';
import { z, ZodType } from 'zod';
import { zodResolver } from '@hookform/resolvers/zod';

import styles from './RegistrationForm.module.css';

/** */
export type FormData = {

	/** */
	email: string;

	/** */
	firstName: string;

	/** */
	lastName: string;

	/** */
	password: string;

	/** */
	retypedPassword: string;
};

/** */
export const RegistrationSchema: ZodType<FormData> = z
	.object({
		email: z.string({ required_error: 'This field is required' }).email('Please provide a valid email'),
		firstName: z.string({ required_error: 'This field is required' }),
		lastName: z.string({ required_error: 'This field is required' }),
		password: z.string({ required_error: 'This field is required' }),
		retypedPassword: z.string({ required_error: 'This field is required' }),
	})
	.refine(data => data.password === data.retypedPassword, {
		message: 'Passwords do not match',
		path: ['retypedPassword'],
	});

/** Registration form component. */
const RegistrationFormComponent: FC = () => {
	const {
		register,
		handleSubmit,
		formState: { errors },
	} = useForm<FormData>({
		mode: 'onBlur',
		resolver: zodResolver(RegistrationSchema),
	});
	const onSubmit: SubmitHandler<FormData> = (registrationData: FormData) => {
		console.log(registrationData);
	};

	return (
		<div className={styles.formWrapper}>
			<h2 className={styles.header}>Register</h2>
			<form onSubmit={handleSubmit(onSubmit)} className={styles.form}>
				<TextField
					label="Email"
					type="email"
					variant="outlined"
					fullWidth
					placeholder="ivan.pupkin@gmail.com"
					{...register('email', { required: true })}
					error={!!errors.email}
					helperText={errors.email ? errors.email.message : ''}
				/>
				<TextField
					label="First name"
					type="text"
					variant="outlined"
					fullWidth
					placeholder="Ivan"
					{...register('firstName')}
					error={!!errors.firstName}
					helperText={errors.firstName ? errors.firstName?.message : ''}
				/>
				<TextField
					label="Last name"
					type="text"
					variant="outlined"
					fullWidth
					placeholder="Pupkin"
					{...register('lastName')}
					error={!!errors.lastName}
					helperText={errors.lastName ? errors.lastName.message : ''}
				/>
				<TextField
					label="Password"
					type="password"
					variant="outlined"
					fullWidth
					placeholder="veryStrongPassW0rd"
					{...register('password')}
					error={!!errors.password}
					helperText={errors.password ? errors.password.message : ''}
				/>
				<TextField
					label="Repeat the password"
					type="password"
					variant="outlined"
					fullWidth
					placeholder="veryStrongPassW0rd"
					{...register('retypedPassword')}
					error={!!errors.retypedPassword}
					helperText={errors.retypedPassword ? errors.retypedPassword.message : ''}
				/>
				<Button
					type="submit"
					variant="outlined"
				>
					Register
				</Button>
			</form>
		</div>
	);
};

/** Memoized registration form. */
export const RegistrationForm = memo(RegistrationFormComponent);

// apps/angular/src/app/features/registration/registration-form.component.ts
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { FormFieldsService } from '@js-camp/angular/core/services/form-fields.service';
import { Registration } from '@js-camp/core/models/registration';
import { AuthorizationApiService } from '@js-camp/angular/core/services/authorization-api.service';

/** Component with form for registration. */
@Component({
	selector: 'camp-registration-form',
	standalone: true,
	templateUrl: './registration-form.component.html',
	styleUrl: './registration-form.component.css',
	changeDetection: ChangeDetectionStrategy.OnPush,
	imports: [
		ReactiveFormsModule,
		MatFormFieldModule,
		MatInputModule,
		MatButtonModule,
	],
})
export class RegistrationFormComponent {

	private formFieldsService = inject(FormFieldsService);

	private authorizationApiService = inject(AuthorizationApiService);

	/** Form for registration. */
	protected registrationForm = new FormGroup({
		email: new FormControl('', { nonNullable: true, validators: [Validators.required, Validators.email] }),
		firstName: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
		lastName: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
		password: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
		retypedPassword: new FormControl('', { nonNullable: true, validators: [Validators.required] }),
	}, { validators: this.formFieldsService.matchFieldsValidator('password', 'retypedPassword') });

	/** */
	protected onRegistrationSubmit(): void {
		const formData = this.registrationForm.getRawValue();

		const registrationData = new Registration({
			email: formData.email,
			firstName: formData.firstName,
			lastName: formData.lastName,
			password: formData.password,
		});
		this.authorizationApiService.register(registrationData);
	}

}

<div class="registration-form-wrapper">
	<h2 class="registration-header">Registration</h2>
	@if (registrationFormGroup) {
		<form
			class="registration-form"
			[formGroup]="registrationFormGroup"
			(ngSubmit)="onRegistrationSubmit()"
		>

			<mat-form-field
				appearance="outline"
				class="registration-form__field"
			>
				<mat-label>Email</mat-label>
				<input
					matInput
					type="email"
					placeholder="ivan.pupkin@gmail.com"
					formControlName="email"
				>
				@if (registrationFormGroup.get('email')?.hasError('required') && registrationFormGroup.get('email')?.touched) {
					<mat-error>Email is required.</mat-error>
				} @else if (registrationFormGroup.get('email')?.hasError('email') && registrationFormGroup.get('email')?.touched) {
					<mat-error>Enter a valid email address.</mat-error>
				}
				@if (registrationFormGroup.get('email')?.hasError('serverError')) {
					<mat-error>{{registrationFormGroup.get('email')?.getError('serverError')}}</mat-error>
				}
			</mat-form-field>

			<mat-form-field
				appearance="outline"
				class="registration-form__field"
			>
				<mat-label>First Name</mat-label>
				<input
					matInput
					type="text"
					placeholder="Ivan"
					formControlName="firstName"
				>
				@if (registrationFormGroup.get('firstName')?.touched && registrationFormGroup.get('firstName')?.hasError('required')) {
					<mat-error>First name is required.</mat-error>
				}
				@if (registrationFormGroup.get('firstName')?.hasError('serverError')) {
					<mat-error>{{registrationFormGroup.get('firstName')?.getError('serverError')}}</mat-error>
				}
			</mat-form-field>

			<mat-form-field
				appearance="outline"
				class="registration-form__field"
			>
				<mat-label>Last Name</mat-label>
				<input
					matInput
					type="text"
					placeholder="Pupkin"
					formControlName="lastName"
				>
				@if (registrationFormGroup.get('lastName')?.touched && registrationFormGroup.get('lastName')?.hasError('required')) {
						<mat-error>Last name is required.</mat-error>
				}
				@if (registrationFormGroup.get('lastName')?.hasError('serverError')) {
					<mat-error>{{registrationFormGroup.get('lastName')?.getError('serverError')}}</mat-error>
				}
			</mat-form-field>

			<mat-form-field
				appearance="outline"
				class="registration-form__field"
			>
				<mat-label>Password</mat-label>
				<input
					matInput
					type="password"
					placeholder="veryStrongPassW0rd"
					formControlName="password"
				>
				@if (registrationFormGroup.get('password')?.touched && registrationFormGroup.get('password')?.hasError('required')) {
					<mat-error>Password is required.</mat-error>
				}
				@if (registrationFormGroup.get('password')?.hasError('serverError')) {
					<mat-error>{{registrationFormGroup.get('password')?.getError('serverError')}}</mat-error>
				}
			</mat-form-field>

			<mat-form-field
				appearance="outline"
				class="registration-form__field"
			>
				<mat-label> Repeat the password</mat-label>
				<input
					matInput
					type="password"
					placeholder="veryStrongPassW0rd"
					formControlName="retypedPassword"
					type="password"
				>
				@if (registrationFormGroup.get('retypedPassword')?.touched && registrationFormGroup.get('retypedPassword')?.hasError('required')) {
					<mat-error>Retyped password is required.</mat-error>
				} @else if (registrationFormGroup.get('retypedPassword')?.hasError('mustMatch')) {
					<mat-error>Passwords must match.</mat-error>
				}
			</mat-form-field>

			@if (registrationFormGroup.hasError('serverError')) {
				<mat-error>{{registrationFormGroup.getError('serverError')}}</mat-error>
			}

			<button
				mat-raised-button
				type="submit"
				[disabled]="registrationFormGroup.invalid"
			>
				Register
			</button>

		</form>
	}
</div>
